# This workflow adds documents to the Rockset collections when a change is made

name: Add docs

on:
  push:
      branches:
        - master

jobs:
  main:

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
            sudo npm install -g @rockset/cli

      - name: Authorize access
        run: |
          rockset auth:add me ${{ secrets.RS2_TOKEN }}

      - name: Add docs
        run: |
          rockset api:documents:addDocuments botw-api creatures --body creatures.json
          rockset api:documents:addDocuments botw-api creatures --body equipment.json
          rockset api:documents:addDocuments botw-api creatures --body materials.json
          rockset api:documents:addDocuments botw-api creatures --body monsters.json
          rockset api:documents:addDocuments botw-api creatures --body treasure.json