# This workflow tests endpoints every hour

name: Add docs

on:
  schedule:
  - cron:  '*/60 * * * *'

jobs:
  main:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test "/" endpoint
      run: |
        source .github/workflows/test_endpoints/functions.sh
        test_endpoint ""

    - name: Test "/entry" enpoint
      run: |
        source .github/workflows//test_endpoints/functions.sh
        test_endpoint "/entry/1"

    - name: Test "/category" endpoint
      run: |
        source .github/workflows//test_endpoints/functions.sh
        test_endpoint "/category/creatures"
