# This workflow tests endpoints every hour

name: Test endpoints

on:
  schedule:
  - cron:  '*/2400 * * * *'

jobs:
  main:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Import functions
      run: |
        source .github/workflows/test_endpoints/functions.sh
    - name: Test "/" endpoint
      run: |
        test_endpoint ""

    - name: Test "/entry" enpoint
      run: |
        test_endpoint "/entry/1"

    - name: Test "/category" endpoint
      run: |
        test_endpoint "/category/creatures"
